# Copyright (C) 2026 — 2026, Ota. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: example
